// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbllyyrcjzfnvzvlbnek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ibGx5eXJjanpmbnZ6dmxibmVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NjYxNzMsImV4cCI6MjA2NjU0MjE3M30.DO68aob3ezz4iLLzyTUmxu4d8JxfKcbWJhpeGuZIZvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);